### ISSUE TITLE
这个插件一直报错def gitSha = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()

### ISSUE THREAD

**Issue by liericiyan** [CycloneAxe/phphub-android#9]
org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl cannot be cast to org.jetbrains.plugins.groovy.lang.psi.api.statements.expressions.literals.GrLiteral
java.lang.ClassCastException: org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl cannot be cast to org.jetbrains.plugins.groovy.lang.psi.api.statements.expressions.literals.GrLiteral
	at com.android.tools.idea.gradle.dsl.parser.GradleDslParser.parse(GradleDslParser.java:157)
	at com.android.tools.idea.gradle.dsl.parser.GradleDslParser.access$100(GradleDslParser.java:50)
	at com.android.tools.idea.gradle.dsl.parser.GradleDslParser$1.visitApplicationStatement(GradleDslParser.java:99)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrApplicationStatementImpl.accept(GrApplicationStatementImpl.java:37)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptGroovyChildren(GroovyPsiElementImpl.java:77)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.blocks.GrBlockImpl.acceptChildren(GrBlockImpl.java:82)
	at com.android.tools.idea.gradle.dsl.parser.GradleDslParser.parse(GradleDslParser.java:91)
	at com.android.tools.idea.gradle.dsl.parser.GradleDslParser.parse(GradleDslParser.java:86)
	at com.android.tools.idea.gradle.dsl.parser.GradleDslParser.access$000(GradleDslParser.java:50)
	at com.android.tools.idea.gradle.dsl.parser.GradleDslParser$1.visitMethodCallExpression(GradleDslParser.java:94)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.path.GrMethodCallExpressionImpl.accept(GrMethodCallExpressionImpl.java:51)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptGroovyChildren(GroovyPsiElementImpl.java:77)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.blocks.GrBlockImpl.acceptChildren(GrBlockImpl.java:82)
	at com.android.tools.idea.gradle.dsl.parser.GradleDslParser.parse(GradleDslParser.java:91)
	at com.android.tools.idea.gradle.dsl.parser.GradleDslParser.parse(GradleDslParser.java:86)
	at com.android.tools.idea.gradle.dsl.parser.GradleDslParser.parse(GradleDslParser.java:53)
	at com.android.tools.idea.gradle.dsl.model.GradleBuildModel$GradleBuildDslFile$1.process(GradleBuildModel.java:181)
	at com.android.tools.idea.gradle.dsl.model.GradleBuildModel$GradleBuildDslFile$1.visitMethodCallExpression(GradleBuildModel.java:158)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.path.GrMethodCallExpressionImpl.accept(GrMethodCallExpressionImpl.java:51)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyPsiElementVisitor.visitElement(GroovyPsiElementVisitor.java:34)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:196)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:779)
	at com.android.tools.idea.gradle.dsl.model.GradleBuildModel$GradleBuildDslFile.parse(GradleBuildModel.java:152)
	at com.android.tools.idea.gradle.dsl.parser.GradleDslFile.parse(GradleDslFile.java:69)
	at com.android.tools.idea.gradle.dsl.model.GradleBuildModel.parseBuildFile(GradleBuildModel.java:54)
	at com.android.tools.idea.gradle.dsl.model.GradleBuildModel.get(GradleBuildModel.java:48)
	at xyz.marcato.ideaplugin.methodscount.MethodsCountFoldingBuilder.buildFoldRegionsWithGradleBuildModel(MethodsCountFoldingBuilder.kt:24)
	at xyz.marcato.ideaplugin.methodscount.MethodsCountFoldingBuilder.buildFoldRegions(MethodsCountFoldingBuilder.kt:63)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:83)
	at com.intellij.lang.folding.CompositeFoldingBuilder.buildFoldRegions(CompositeFoldingBuilder.java:60)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:83)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:265)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:250)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getUpdateResult(FoldingUpdate.java:120)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.access$000(FoldingUpdate.java:56)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate$2.compute(FoldingUpdate.java:108)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate$2.compute(FoldingUpdate.java:103)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:53)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:43)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:96)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:102)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegions(CodeFoldingManagerImpl.java:344)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:326)
	at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:42)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1103)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:189)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by xiaolongyuan** [comment]
一样 可能是gradle 找不到git的环境变量

**Comment by liericiyan** [comment]
@xiaolongyuan 把这行注掉，然后在注掉引用到对应变量的地方就可以了，已经正常编译

**Comment by xiaolongyuan** [comment]
@liericiyan 没太明白 我是直接弄了个硬编码 作者可能在linux/mac上编码的  win上有问题 其实那个就是拿一下当前最新提交的记录缩略，无伤大雅

**Comment by liericiyan** [comment]
@xiaolongyuan 嗯，能正常编译运行就行，我也是在windows上开发的

**Comment by xiaolongyuan** [comment]
共勉
